# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/car.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

    - &Glass1
        Name: Glass1MSP
        ID: Glass1MSP
        MSPDir: crypto-config/peerOrganizations/glass1.car.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Glass1MSP.admin', 'Glass1MSP.peer', 'Glass1MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Glass1MSP.admin', 'Glass1MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Glass1MSP.admin')"
        AnchorPeers:
            - Host: peer0.glass1.car.com
              Port: 7051

    - &Led1
        Name: Led1MSP
        ID: Led1MSP
        MSPDir: crypto-config/peerOrganizations/led1.car.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Led1MSP.admin', 'Led1MSP.peer', 'Led1MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Led1MSP.admin', 'Led1MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Led1MSP.admin')"
        AnchorPeers:
            - Host: peer0.led1.car.com
              Port: 7051

    - &Headlight1
        Name: Headlight1MSP
        ID: Headlight1MSP
        MSPDir: crypto-config/peerOrganizations/headlight1.car.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Headlight1MSP.admin', 'Headlight1MSP.peer', 'Headlight1MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Headlight1MSP.admin', 'Headlight1MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Headlight1MSP.admin')" 
        AnchorPeers:
            - Host: peer0.headlight1.car.com
              Port: 7051

    - &Mirror1
        Name: Mirror1MSP
        ID: Mirror1MSP
        MSPDir: crypto-config/peerOrganizations/mirror1.car.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Mirror1MSP.admin', 'Mirror1MSP.peer', 'Mirror1MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Mirror1MSP.admin', 'Mirror1MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Mirror1MSP.admin')" 
        AnchorPeers:
            - Host: peer0.mirror1.car.com
              Port: 7051

Capabilities:
    Channel: &ChannelCapabilities
        V1_4_3: true
        V1_3: false
        V1_1: false
    Orderer: &OrdererCapabilities
        V1_4_2: true
        V1_1: false
    Application: &ApplicationCapabilities
        V1_4_2: true
        V1_3: false
        V1_2: false
        V1_1: false

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
        - orderer.car.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB

    Kafka:
        Brokers:
            - 127.0.0.1:9092

    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:

    OrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Glass1
                    - *Led1
                    - *Headlight1
                    - *Mirror1
    ChannelOne:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Glass1
                - *Led1
                - *Headlight1
            Capabilities:
                <<: *ApplicationCapabilities
    ChannelTwo:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Glass1
                - *Mirror1
            Capabilities:
                <<: *ApplicationCapabilities
