OrdererOrgs:
  - Name: Orderer
    Domain: car.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Glass
    Domain: glass1.car.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Led
    Domain: led1.car.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Headlight
    Domain: headlight1.car.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Mirror
    Domain: mirror1.car.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
