# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.car.com:
    container_name: orderer.car.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/car.com/orderers/orderer.car.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/car.com/orderers/orderer.car.com/tls/:/var/hyperledger/orderer/tls
        - orderer.car.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.glass1.car.com:
    container_name: peer0.glass1.car.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.glass1.car.com
      - CORE_PEER_ADDRESS=peer0.glass1.car.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.glass1.car.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.led1.car.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.glass1.car.com:7051
      - CORE_PEER_LOCALMSPID=Glass1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/glass1.car.com/peers/peer0.glass1.car.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/glass1.car.com/peers/peer0.glass1.car.com/tls:/etc/hyperledger/fabric/tls
        - peer0.glass1.car.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer0.led1.car.com:
    container_name: peer0.led1.car.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.led1.car.com
      - CORE_PEER_ADDRESS=peer0.led1.car.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.led1.car.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.led1.car.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.glass1.car.com:7051
      - CORE_PEER_LOCALMSPID=Led1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/led1.car.com/peers/peer0.led1.car.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/led1.car.com/peers/peer0.led1.car.com/tls:/etc/hyperledger/fabric/tls
        - peer0.led1.car.com:/var/hyperledger/production
    ports:
      - 9051:7051

  peer0.headlight1.car.com:
    container_name: peer0.headlight1.car.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.headlight1.car.com
      - CORE_PEER_ADDRESS=peer0.headlight1.car.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.headlight1.car.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.headlight1.car.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.glass1.car.com:7051
      - CORE_PEER_LOCALMSPID=Headlight1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/headlight1.car.com/peers/peer0.headlight1.car.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/headlight1.car.com/peers/peer0.headlight1.car.com/tls:/etc/hyperledger/fabric/tls
        - peer0.headlight1.car.com:/var/hyperledger/production
    ports:
      - 11051:7051

  peer0.mirror1.car.com:
    container_name: peer0.mirror1.car.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.mirror1.car.com
      - CORE_PEER_ADDRESS=peer0.mirror1.car.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.mirror1.car.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.mirror1.car.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.glass1.car.com:7051
      - CORE_PEER_LOCALMSPID=Mirror1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/mirror1.car.com/peers/peer0.mirror1.car.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/mirror1.car.com/peers/peer0.mirror1.car.com/tls:/etc/hyperledger/fabric/tls
        - peer0.mirror1.car.com:/var/hyperledger/production
    ports:
      - 12051:7051

